on: 
  push:
    brenches:
    - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        
    - name: 🚢 Docker Update
      run: |
        ls /home/ubuntu
        cd /home/ubuntu/github-actions-ftp || exit 1
        sudo docker compose down || exit 1
        sudo docker compose up -d || exit 1